# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

pkgname: mocks
mockname: "{{.InterfaceName}}"
filename: "{{snakecase .InterfaceName}}.go"
dir: "{{.InterfaceDirRelative}}/mocks"
template-data:
  boilerplate-file: ./tools/config/boilerplate.txt
  with-expecter: true
force-file-write: true

packages:
  github.com/absmach/supermq/api/grpc/clients/v1:
    interfaces:
      ClientsServiceClient:
        config:
          dir: "./clients/mocks"
          mockname: "ClientsServiceClient"
          filename: "clients_client.go"
  github.com/absmach/supermq/api/grpc/domains/v1:
    interfaces:
      DomainsServiceClient:
        config:
          dir: "./domains/mocks"
          mockname: "DomainsServiceClient"
          filename: "domains_client.go"
  github.com/absmach/supermq/api/grpc/token/v1:
    interfaces:
      TokenServiceClient:
        config:
          dir: "./auth/mocks"
          mockname: "TokenServiceClient"
          filename: "token_client.go"
  github.com/absmach/supermq/api/grpc/channels/v1:
    interfaces:
      ChannelsServiceClient:
        config:
          dir: "./channels/mocks"
          mockname: "ChannelsServiceClient"
          filename: "channels_client.go"
  github.com/absmach/supermq/api/grpc/groups/v1:
    interfaces:
      GroupsServiceClient:
        config:
          dir: "./groups/mocks"
          mockname: "GroupsServiceClient"
          filename: "groups_client.go"
  github.com/absmach/supermq/pkg/sdk:
    interfaces:
      SDK:
        config:
          dir: "./pkg/sdk/mocks"
          mockname: "SDK"
          filename: "sdk.go"

  github.com/absmach/supermq/certs/pki/amcerts:
    interfaces:
      Agent:
        config:
          dir: "./certs/mocks"
          mockname: "Agent"
          filename: "pki.go"
  github.com/absmach/supermq/auth:
    interfaces:
      Authz:
      Cache:
      Hasher:
      KeyRepository:
      PATS:
      PATSRepository:
      Service:
  github.com/absmach/supermq/certs:
    interfaces:
      Service:
  github.com/absmach/supermq/channels:
    interfaces:
      Cache:
      Repository:
      Service:
  github.com/absmach/supermq/channels/private:
    interfaces:
      Service:
  github.com/absmach/supermq/clients:
    interfaces:
      Repository:
      Cache:
      Service:
  github.com/absmach/supermq/clients/private:
    interfaces:
      Service:
  github.com/absmach/supermq/consumers:
    interfaces:
      Notifier:
  github.com/absmach/supermq/domains:
    interfaces:
      Repository:
      Cache:
      Service:
  github.com/absmach/supermq/domains/private:
    interfaces:
      Service:
  github.com/absmach/supermq/groups:
    interfaces:
      Repository:
      Service:
  github.com/absmach/supermq/groups/private:
    interfaces:
      Service:
  github.com/absmach/supermq/journal:
    interfaces:
      Repository:
      Service:
  github.com/absmach/supermq/pkg/authn:
    interfaces:
      Authentication:
  github.com/absmach/supermq/pkg/authz:
    interfaces:
      Authorization:
  github.com/absmach/supermq/pkg/events:
    interfaces:
      Publisher:
      Subscriber:
  github.com/absmach/supermq/pkg/messaging:
    interfaces:
      PubSub:
  github.com/absmach/supermq/pkg/oauth2:
    interfaces:
      Provider:
  github.com/absmach/supermq/pkg/policies:
    interfaces:
      Evaluator:
      Service:
  github.com/absmach/supermq/pkg/roles:
    interfaces:
      Provisioner:
      RoleManager:
      Repository:
  github.com/absmach/supermq/pkg/callout:
    interfaces:
      Callout:
  github.com/absmach/supermq/readers:
    interfaces:
      MessageRepository:
  github.com/absmach/supermq/users:
    interfaces:
      Emailer:
      Hasher:
      Repository:
      Service:
